name: spiral
description: "Developer assessment task."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  get: ^4.6.6
  flutter_svg: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/dummy/

  fonts:
   - family: Satoshi
     fonts:
       - asset: assets/fonts/Satoshi-Light.otf
         weight: 300
       - asset: assets/fonts/Satoshi-Regular.otf
         weight: 400
       - asset: assets/fonts/Satoshi-Medium.otf
         weight: 500
       - asset: assets/fonts/Satoshi-Bold.otf
         weight: 700
       - asset: assets/fonts/Satoshi-Black.otf
         weight: 900


